-- Add transcription column to knowledge_files table for audio file transcriptions
ALTER TABLE public.knowledge_files
ADD COLUMN IF NOT EXISTS transcription TEXT,
ADD COLUMN IF NOT EXISTS transcription_status TEXT CHECK (transcription_status IN ('pending', 'processing', 'completed', 'failed')),
ADD COLUMN IF NOT EXISTS transcription_error TEXT,
ADD COLUMN IF NOT EXISTS transcribed_at TIMESTAMP WITH TIME ZONE;

-- Create index for faster queries on transcription status
CREATE INDEX IF NOT EXISTS idx_knowledge_files_transcription_status 
ON public.knowledge_files(transcription_status) 
WHERE type = 'audio';

-- Add comment for documentation
COMMENT ON COLUMN public.knowledge_files.transcription IS 'Transcription text for audio files generated by OpenAI Whisper';
COMMENT ON COLUMN public.knowledge_files.transcription_status IS 'Status of transcription: pending, processing, completed, or failed';
COMMENT ON COLUMN public.knowledge_files.transcription_error IS 'Error message if transcription failed';
COMMENT ON COLUMN public.knowledge_files.transcribed_at IS 'Timestamp when transcription was completed';

